
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author OMEN
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRoom = new javax.swing.JButton();
        btnCCI = new javax.swing.JButton();
        btnCCO = new javax.swing.JButton();
        btnCDB = new javax.swing.JButton();
        btnDeconnect = new javax.swing.JButton();
        btnQuiitter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Accueil");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRoom.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        btnRoom.setForeground(new java.awt.Color(153, 0, 0));
        btnRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manage room.png"))); // NOI18N
        btnRoom.setText("Gérer la salle");
        btnRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomActionPerformed(evt);
            }
        });
        getContentPane().add(btnRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnCCI.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        btnCCI.setForeground(new java.awt.Color(153, 0, 0));
        btnCCI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Customer Registration & Check IN.png"))); // NOI18N
        btnCCI.setText("ARRIVé du client");
        btnCCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCCIActionPerformed(evt);
            }
        });
        getContentPane().add(btnCCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, -1));

        btnCCO.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        btnCCO.setForeground(new java.awt.Color(153, 0, 0));
        btnCCO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Customer Check Out.png"))); // NOI18N
        btnCCO.setText("Départ du client");
        btnCCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCCOActionPerformed(evt);
            }
        });
        getContentPane().add(btnCCO, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, -1));

        btnCDB.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        btnCDB.setForeground(new java.awt.Color(153, 0, 0));
        btnCDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Customer Details Bill.png"))); // NOI18N
        btnCDB.setText(" Facture CLIENT");
        btnCDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCDBActionPerformed(evt);
            }
        });
        getContentPane().add(btnCDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, -1));

        btnDeconnect.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        btnDeconnect.setForeground(new java.awt.Color(153, 0, 0));
        btnDeconnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        btnDeconnect.setText("Deconnecter");
        btnDeconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeconnectActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeconnect, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, -1, -1));

        btnQuiitter.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        btnQuiitter.setForeground(new java.awt.Color(153, 0, 0));
        btnQuiitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        btnQuiitter.setText("Quitter");
        btnQuiitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuiitterActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuiitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pageHome.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeconnectActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Souhaitez-vous deconnecter?","select",JOptionPane.YES_NO_OPTION);
        if (a==0){
            setVisible(false);
            new LogIn().setVisible(true);
        }
    }//GEN-LAST:event_btnDeconnectActionPerformed

    private void btnQuiitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuiitterActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Voulez-vous Quitter l'Application?","select",JOptionPane.YES_NO_OPTION);
        if(a==0) System.exit(0);
    }//GEN-LAST:event_btnQuiitterActionPerformed

    private void btnRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomActionPerformed
        // TODO add your handling code here:
        new ManageRoom().setVisible(true);
    }//GEN-LAST:event_btnRoomActionPerformed

    private void btnCCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCCIActionPerformed
        // TODO add your handling code here:
        new CustomerCheckIN().setVisible(true);
    }//GEN-LAST:event_btnCCIActionPerformed

    private void btnCCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCCOActionPerformed
        // TODO add your handling code here:
        new CustomerChechOut().setVisible(true); 
    }//GEN-LAST:event_btnCCOActionPerformed

    private void btnCDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCDBActionPerformed
        // TODO add your handling code here:
        new DetailsClient().setVisible(true);
    }//GEN-LAST:event_btnCDBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCCI;
    private javax.swing.JButton btnCCO;
    private javax.swing.JButton btnCDB;
    private javax.swing.JButton btnDeconnect;
    private javax.swing.JButton btnQuiitter;
    private javax.swing.JButton btnRoom;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
