
import javax.swing.JOptionPane;
import project.InsertUpdateDelete;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author OMEN
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnclose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        txtmail = new javax.swing.JTextField();
        txtmdp = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txtqs = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtreponse = new javax.swing.JTextField();
        txtAdd = new javax.swing.JTextField();
        btnInscription = new javax.swing.JButton();
        btnConnect = new javax.swing.JButton();
        btnForgetMDP = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INSCRIPTION");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 760));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1317, 0, 39, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INSCRIPTION");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 372, 39));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nom");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 130, 30));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 270, 130, 30));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mot de passe");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 190, 30));

        txtnom.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        getContentPane().add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, 300, 30));

        txtmail.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 300, 30));

        txtmdp.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        getContentPane().add(txtmdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 300, 30));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Question de securité");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 220, 30));

        txtqs.setFont(new java.awt.Font("Verdana", 1, 8)); // NOI18N
        txtqs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is the name of your first pet?", "What was your first car?", "What elementary scholol did you attend?", "What is the name of the town where you were born?" }));
        txtqs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqsActionPerformed(evt);
            }
        });
        getContentPane().add(txtqs, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, 300, 30));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Reponse");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 140, 30));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Addresse");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 160, -1));

        txtreponse.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtreponse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtreponseActionPerformed(evt);
            }
        });
        getContentPane().add(txtreponse, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 300, 30));

        txtAdd.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        getContentPane().add(txtAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, 300, 30));

        btnInscription.setBackground(new java.awt.Color(102, 102, 255));
        btnInscription.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnInscription.setForeground(new java.awt.Color(255, 255, 255));
        btnInscription.setText("S'inscrire");
        btnInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscriptionActionPerformed(evt);
            }
        });
        getContentPane().add(btnInscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 130, 30));

        btnConnect.setBackground(new java.awt.Color(102, 102, 255));
        btnConnect.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnConnect.setForeground(new java.awt.Color(255, 255, 255));
        btnConnect.setText("Connectez-vous");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });
        getContentPane().add(btnConnect, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 480, 160, 30));

        btnForgetMDP.setBackground(new java.awt.Color(102, 102, 255));
        btnForgetMDP.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnForgetMDP.setForeground(new java.awt.Color(255, 255, 255));
        btnForgetMDP.setText("Mot de passe oublié?");
        btnForgetMDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgetMDPActionPerformed(evt);
            }
        });
        getContentPane().add(btnForgetMDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 540, 200, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signup.PNG"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 1360, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnForgetMDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgetMDPActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ForgetPasseword().setVisible(true);
    }//GEN-LAST:event_btnForgetMDPActionPerformed

    private void txtmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmailActionPerformed

    private void txtqsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqsActionPerformed

    private void txtreponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreponseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtreponseActionPerformed

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new LogIn().setVisible(true);
    }//GEN-LAST:event_btnConnectActionPerformed

    private void btnInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscriptionActionPerformed
        // TODO add your handling code here:
        String nom = txtnom.getText();
        String email = txtmail.getText();
        String mdp = txtmdp.getText();
        String securityQuestion = (String)txtqs.getSelectedItem();
        String reponse = txtreponse.getText();
        String Add = txtAdd.getText();
        if(nom.equals("")|| email.equals("")|| mdp.equals("")|| securityQuestion.equals("")|| reponse.equals("")||Add.equals("")){
            JOptionPane.showMessageDialog(null,"Tous les champs sont obligatoires");
        }else{
            String Query;
            Query = "insert into users values('"+nom+"', '"+email+"', '"+mdp+"','"+securityQuestion+"', '"+reponse+"','"+Add+"','false')";
            InsertUpdateDelete.setData(Query, "Inscription réussie!");
            setVisible(false);
            new SignUp().setVisible(true);
        }
    }//GEN-LAST:event_btnInscriptionActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Souhaiter-vous fermer l'application?","select",JOptionPane.YES_NO_OPTION);
        if(a==0)System.exit(0);
    }//GEN-LAST:event_btncloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnForgetMDP;
    private javax.swing.JButton btnInscription;
    private javax.swing.JButton btnclose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtAdd;
    private javax.swing.JTextField txtmail;
    private javax.swing.JPasswordField txtmdp;
    private javax.swing.JTextField txtnom;
    private javax.swing.JComboBox<String> txtqs;
    private javax.swing.JTextField txtreponse;
    // End of variables declaration//GEN-END:variables
}
